import { configDotenv } from "dotenv";
configDotenv();
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";

import { cn } from "@/lib/utils";
import { GlobalProvider } from "@/providers/index";

import type { Metadata } from "next";

import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("antialiased", geistMono.variable, geistSans.variable, "font-sans")}
    >
      <body className="bg-sidebar">
        <GlobalProvider>{children}</GlobalProvider>
        <ToastContainer theme="light" />
      </body>
    </html>
  );
}
